yuki-zaki19/freemarket_sample_56b

- config/database.yml
- config/unicorn.rb
> [WIP] third commit

- app/assets/stylesheets/products/_show.scss
- app/views/products/show.html.haml
商品詳細ページの実装（フロント）
アプリケーションに必要なため
> [WIP] yakushi-commit

- app/assets/javascripts/sellers.coffee
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/sellers/_sellers.scss
- app/controllers/sellers_controller.rb
- app/helpers/sellers_helper.rb
- app/models/seller.rb
- config/routes.rb
- db/migrate/20190806012242_create_sellers.rb
- spec/controllers/sellers_controller_spec.rb
- spec/factories/sellers.rb
- spec/helpers/sellers_helper_spec.rb
- spec/models/seller_spec.rb
SELLERモデルとコントローラーの作成
アプリケーションに必要なため
> [WIP] SELLERモデルとコントローラーの作成

- app/assets/stylesheets/sellers/_show.scss
- app/views/sellers/show.html.haml
- db/migrate/20190806012242_create_sellers.rb
- db/schema.rb
商品購入確認ページ実装（フロント）
アプリケーションに必要なため
> [WIP] 商品購入確認ページ実装（フロント）

- app/assets/stylesheets/users/_index.scss
- app/views/users/index.html.haml
ユーザーマイページのフロントエンド作成
アプリケーションに必要なため
https://gyazo.com/1415f26e1f8b5cc40179c0ffa1410a60
> sato commit

- app/assets/stylesheets/products/_new.scss
- app/views/products/new.html.haml
商品出品ページのマークアップ
商品出品のためのマークアップの作成のため
https://gyazo.com/c0b225417dae639dcb7ba97983ef9e07
> exhibition_markup

- README.md
- app/assets/javascripts/identifications.coffee
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/identifications/_identifications.scss
- app/assets/stylesheets/identifications/_new.scss
- app/assets/stylesheets/users/_index.scss
- app/controllers/identifications_controller.rb
- app/helpers/identifications_helper.rb
- app/models/identification.rb
- app/views/identifications/new.html.haml
- config/routes.rb
- db/migrate/20190806101357_create_identifications.rb
- db/schema.rb
- spec/controllers/identifications_controller_spec.rb
- spec/factories/identifications.rb
- spec/helpers/identifications_helper_spec.rb
- spec/models/identification_spec.rb
ユーザー本人確認ページのビュー作成
#Why
ユーザー本人確認に必要なため
https://gyazo.com/89f84c712b067ab168e9ba01868eea98
> sato2 commit

- app/assets/stylesheets/products/_new.scss
- app/views/products/_bigicon.html.haml
出品ボタンの作成
ユーザーが簡単に出品ページに遷移できようhにするため
> exhibition_btn_empty_commit

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/identifications/_new.scss
- app/assets/stylesheets/users/_edit.scss
- app/controllers/users_controller.rb
- app/views/users/edit.html.haml
ユーザープロフィール編集ページのビュー作成
ユーザーがプロフィール編集をできるようにするため
https://gyazo.com/00f7458af18eb19556ec64817b26a47c
> sato3 commit

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/users/_card.scss
- app/controllers/users_controller.rb
- app/views/users/card.html.haml
- config/routes.rb
#What
クレジットカード登録ページの作成
#Why
クレジットカードを登録するため
https://gyazo.com/13d6c148b6daea64088aa60473647447
> sato5 commit

- app/assets/stylesheets/users/_new.scss
- app/assets/stylesheets/users/_new_2.scss
- app/views/devise/registrations/new.html.haml
> [WIP]create_user_registration_empty_commit

- app/assets/stylesheets/users/_new_3.scss
- app/views/users/new_3.html.haml
- config/routes.rb
ユーザー新規登録画面の実装（電話番号）
アプリケーションに必要なため
> [WIP] ユーザー新規登録画面の実装（電話番号）

- app/assets/stylesheets/users/_new_4.scss
- app/views/users/new_4.html.haml
- config/routes.rb
ユーザー新規登録ページのフロント実装#4（お届け先住所）
アプリケーションに必要なため
> [WIP]ユーザー新規登録ページのフロント実装#4（お届け先住所）

- app/assets/stylesheets/users/_new_2.scss
- app/views/devise/registrations/new.html.haml
ユーザー新規登録ページの実装
ユーザーが登録できるようにするため
> [WIP]create_user_registration_empty_commit2

- app/assets/stylesheets/products/_index.scss
- app/assets/stylesheets/users/_footer.scss
- app/views/products/index.html.haml
- app/views/users/_footer.html.haml
> [WIP]トップページのフッター

- app/assets/stylesheets/users/_new.scss
- app/views/users/new.html.haml
> ユーザー新規登録画面一ページ目のビュー修正

- app/assets/javascripts/product_new.js
- app/assets/stylesheets/products/_new.scss
- app/views/products/new.html.haml
> exhibition-server-first-commit

- app/assets/javascripts/header_category.js
- app/assets/stylesheets/products/new.json.jbuilder
- app/controllers/products_controller.rb
- app/models/category.rb
- app/models/product.rb
カテゴリーをマウスオーバーで表示させる
よりUSERに使いやすくするため
> “commit11”

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/products/_breadcrumbs.scss
- app/assets/stylesheets/users/_exhibit.scss
- app/assets/stylesheets/users/_index.scss
- app/controllers/users_controller.rb
- app/views/identifications/new.html.haml
- app/views/products/_breadcrumbs.html.haml
- app/views/products/_header.html.haml
- app/views/users/card.html.haml
- app/views/users/edit.html.haml
- app/views/users/exhibit.html.haml
- app/views/users/logout.html.haml
- app/views/users/news.html.haml
- app/views/users/past.html.haml
- app/views/users/sale.html.haml
- app/views/users/task.html.haml
- app/views/users/trade.html.haml
- app/views/users/transaction.html.haml
- config/breadcrumbs.rb
- config/routes.rb
パンくずリストの作成
ユーザーに使いやすくして、現時点の場所を知らせるため
> [WIP]pankuzu-list-create

- app/assets/javascripts/product_new.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/products/_bigicon.scss
- app/assets/stylesheets/products/_new.scss
- app/views/products/_bigicon.html.haml
- app/views/users/index.html.haml
出品ボタンのrenderファイルの作成
いくつかに出てくる出品ボタンをrenderで表示させるため
> [WIP]create_render_bigiconbutton_empty_commit

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/products/_all_categories.scss
- app/assets/stylesheets/products/_index.scss
- app/assets/stylesheets/products/_show.scss
- app/controllers/products_controller.rb
- app/models/product.rb
- app/views/products/all_categories.html.haml
- app/views/products/index.html.haml
- app/views/products/show.html.haml
> [WIP] 商品一覧の画像表示

- app/assets/stylesheets/users/_header.scss
- app/controllers/users_controller.rb
- app/views/identifications/new.html.haml
- app/views/products/_breadcrumbs.html.haml
- app/views/products/_header.html.haml
- app/views/products/index.html.haml
- app/views/products/show.html.haml
- app/views/sellers/show.html.haml
- app/views/users/card.html.haml
- app/views/users/deliver.html.haml
- app/views/users/exhibit.html.haml
- app/views/users/index.html.haml
- app/views/users/logout.html.haml
- app/views/users/new.html.haml
- app/views/users/news.html.haml
- app/views/users/past.html.haml
- app/views/users/sale.html.haml
- app/views/users/task.html.haml
- app/views/users/trade.html.haml
- app/views/users/transaction.html.haml
- config/breadcrumbs.rb
- config/routes.rb
- db/migrate/20190817030858_add_comment_to_users.rb
- db/schema.rb
それぞれのページをつなげるためリンクをつける
ページのルーティングがボタンだけで行えるように
> “commit12”

- app/assets/stylesheets/users/_new_2.scss
- app/controllers/photos_controller.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.haml
- app/views/identifications/edit.html.haml
- app/views/identifications/new.html.haml
- app/views/products/_breadcrumbs.html.haml
- app/views/users/card.html.haml
- app/views/users/deliver.html.haml
- app/views/users/edit.html.haml
- app/views/users/exhibit.html.haml
- app/views/users/index.html.haml
- app/views/users/logout.html.haml
- app/views/users/news.html.haml
- app/views/users/sale.html.haml
- app/views/users/task.html.haml
- app/views/users/trade.html.haml
- app/views/users/transaction.html.haml
- config/breadcrumbs.rb
- config/routes.rb
ユーザーの本人情報を登録する
本人情報をわかるようにするため
> “commit13”

- app/controllers/identifications_controller.rb
- app/views/identifications/edit.html.haml
- app/views/users/deliver.html.haml
- app/views/users/edit.html.haml
本人情報の登録を機能させる
登録と編集をできるようにするため
> “commit14”

- app/assets/stylesheets/users/_new.scss
- app/controllers/identifications_controller.rb
- app/controllers/photos_controller.rb
- app/controllers/sellers_controller.rb
- app/controllers/users_controller.rb
- app/views/users/new.html.haml
ログイン時と未ログイン時の操作に制限をかける
特定されていないユーザーの操作を制限するため
> “commit15”

- app/assets/javascripts/header_category.js
- app/assets/javascripts/product_new.js
- app/assets/stylesheets/products/_new.scss
- app/views/products/new.html.haml
出品機能ページの最終調整
出品機能のクオリティーを上げるため
https://9.gigafile.nu/0826-ba16511115e99d25301c3924e11d31c25
> last_exibition_create_server_empty_commit

- app/assets/javascripts/header_category.js
> [WIP]modify_exhibition_server_empty_commit

- app/controllers/photos_controller.rb
- app/views/devise/registrations/new.html.haml
- db/migrate/20190819104206_add_phone_number_to_identifications.rb
- db/migrate/20190819105730_change_data_phone_number_to_user.rb
- db/schema.rb
identificationテープルに電話番号カラムを追加して登録させる
本物に近づけるため
> “commit16”

- app/assets/javascripts/token.js
- app/views/layouts/application.html.haml
payjpの実装
クレジットカードでの購入ができるようにするため
> [WIP]payjpの実装

- app/controllers/users/omniauth_callbacks_controller.rb
- app/models/user.rb
> [WIP]SNS認証修正

- app/assets/stylesheets/users/_sign_in.scss
- app/views/devise/sessions/new.html.haml
- app/views/users/deliver.html.haml
> “commit18”

- app/assets/javascripts/payjp.js
- app/assets/javascripts/product_new.js
出品した本人が商品を購入できないようにコントローラーで対策
購入したら出品一覧には出さないように編集
購入機能の能力向上のため
> [WIP]購入機能の追加編集

- app/assets/stylesheets/products/_show.scss
- app/controllers/products_controller.rb
- app/controllers/sellers_controller.rb
- app/controllers/users_controller.rb
- app/views/products/show.html.haml
- app/views/users/sale.html.haml
- app/views/users/trade.html.haml
- config/routes.rb
出品者以外のユーザーが編集削除できないようにする
編集削除されては困るため
> “commit19”

- app/controllers/photos_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/models/user.rb
> [WIP]SNS認証の修正

- app/assets/javascripts/product_new.js
> [WIP]出品機能の画像機能の編集

- app/assets/javascripts/product_edit.js
> [WIP]画像投稿機能の実装

- app/assets/javascripts/product_edit.js
- app/assets/javascripts/product_new.js
- app/assets/stylesheets/products/_edit_modal.scss
- app/controllers/products_controller.rb
- app/views/products/_new_form.html.haml
> [WIP]商品編集機能の削除ボタンの実装
